language: go
sudo: required

services:
  - docker

script:
  - docker pull deltaskelta/alpine-stress
  - go get github.com/golang/dep/cmd/dep
  - dep ensure
  - go test ./cmd
  - go test 
  - go install
